### ISSUE TITLE
[GDGSGOM Support] Create new logins for Jasper reports 2023

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/GDGSGOM#13]
## Support ticket 
https://avni.freshdesk.com/a/tickets/3406

## Task -
Create Jasper login for the mentioned users to access GDGSGOM 2023 reports. Share the created userIDs and password for them in the comments.

- [x] 1. Name: Sunil Chavan
 Mob.: 8689980444
Email ID: sec.wcd@maharashtra.gov.in

- [ ] 2. Name : Prakash Patil
Number : 9359653647
Email ID: pranipatil5668@gmail.com

- [ ] 3. Name : Parag Pandit
Number :9699975092
Email ID: rajanbele7@gmail.com

- [ ] 4. Name: Suresh Tonge
Mob.: 8080660899
Email ID: suresh.tonge.82@gmail.com
