### ISSUE TITLE
Checklist - Live Org

### ISSUE THREAD

**Issue by AnjaliBhagabati** [avniproject/GDGSGOM#20]
[ ] OTP to be enabled for Mobile Number Verification in Farmer Registration
- [ ] Glific Integration
- [ ] Financial year change
- [ ] PDF Upload
- [ ] Filter by location
- [ ] Search Feature
- [ ] Translation (Hindi, English, Marathi, Kannada)
- [ ] Reports Changes

Note: **Do this for RWB24uat and gdgs24uat on RWB infra**
